/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patients */
        get: operations["get_patients_api_patients_get"];
        put?: never;
        /** Create Patient */
        post: operations["create_patient_api_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Patient */
        get: operations["search_patient_api_patients_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient */
        get: operations["get_patient_api_patients__patient_serial__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Note */
        post: operations["set_note_api_patients__patient_serial__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Medication */
        post: operations["add_medication_api_patients__patient_serial__medications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/medications/{medication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Medication */
        put: operations["update_medication_api_patients__patient_serial__medications__medication_id__put"];
        post?: never;
        /** Delete Medication */
        delete: operations["delete_medication_api_patients__patient_serial__medications__medication_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Vitals */
        post: operations["add_vitals_api_patients__patient_serial__vitals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Lab */
        post: operations["add_lab_api_patients__patient_serial__labs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/diagnoses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Diagnosis */
        post: operations["add_diagnosis_api_patients__patient_serial__diagnoses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/allergies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Allergies */
        put: operations["update_allergies_api_patients__patient_serial__allergies_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Visit */
        put: operations["update_visit_api_patients_visits_put"];
        /** Set Visit */
        post: operations["set_visit_api_patients_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_serial}/visits/{visit_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visit Report */
        get: operations["get_visit_report_api_patients__patient_serial__visits__visit_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/overview/{patient_serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_agents_overview__patient_serial__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Recommendations */
        post: operations["get_recommendations_api_agents_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Medications */
        post: operations["get_medications_api_agents_medications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/schedule-followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Visit */
        post: operations["schedule_visit_api_agents_schedule_followup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_api_auth_google_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_auth_google_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_api_dashboard_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breakdown */
        get: operations["get_breakdown_api_dashboard_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/lab-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Alerts */
        get: operations["get_lab_alerts_api_dashboard_lab_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/top-diagnoses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Diagnoses */
        get: operations["get_top_diagnoses_api_dashboard_top_diagnoses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIOverview */
        AIOverview: {
            /** Critical Alerts */
            critical_alerts: string[];
            /** Overview */
            overview: string;
            /** Suggested Questions */
            suggested_questions: string[];
        };
        /** AIOverviewResponse */
        AIOverviewResponse: {
            /** Patient Serial */
            patient_serial: string;
            ai_overview: components["schemas"]["AIOverview"];
            /** Chroma Sources */
            chroma_sources: number;
        };
        /** ActiveMedications */
        ActiveMedications: {
            /** Name */
            name: string;
            /** Dosage */
            dosage: string;
            /** Frequency */
            frequency: string;
            /** Reason */
            reason: string;
        };
        /** AddDiagnosis */
        AddDiagnosis: {
            /** Visit Id */
            visit_id: string;
            /** Diagnosing Doctors Serial Number */
            diagnosing_doctors_serial_number: string;
            /** Diagnosis Code */
            diagnosis_code: string;
            /** Diagnosis Name */
            diagnosis_name: string;
            /**
             * Diagnosis Type
             * @enum {string}
             */
            diagnosis_type: "primary" | "secondary" | "chronic" | "acute";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "resolved" | "chronic";
            /** Diagnosed Date */
            diagnosed_date: string;
            /** Resolved Date */
            resolved_date?: string | null;
        };
        /** AddLabResult */
        AddLabResult: {
            /** Visit Id */
            visit_id: string;
            /** Ordering Doctors Serial Number */
            ordering_doctors_serial_number: string;
            /** Test Name */
            test_name: string;
            /** Result Value */
            result_value: string;
            /** Unit */
            unit?: string | null;
            /** Reference Range */
            reference_range: string;
            /**
             * Result Status
             * @enum {string}
             */
            result_status: "normal" | "abnormal" | "critical" | "pending";
            /** Tested Date */
            tested_date: string;
            /** Received Date */
            received_date: string;
        };
        /** AddMedication */
        AddMedication: {
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /** Medication Name */
            medication_name: string;
            /** Generic Name */
            generic_name: string;
            /** Dosage */
            dosage: string;
            /** Frequency */
            frequency: string;
            /** Start Date */
            start_date: string;
            /** Prescribed For */
            prescribed_for: string;
            /** Instructions */
            instructions: string;
            /** End Date */
            end_date?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "discontinued" | "completed" | "hold";
        };
        /** AddVitalSigns */
        AddVitalSigns: {
            /** Visit Id */
            visit_id: string;
            /** Blood Pressure Systolic */
            blood_pressure_systolic?: number | null;
            /** Blood Pressure Diastolic */
            blood_pressure_diastolic?: number | null;
            /** Heart Rate */
            heart_rate?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Respiratory Rate */
            respiratory_rate?: number | null;
            /** Oxygen Saturation */
            oxygen_saturation?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Pain Level */
            pain_level?: number | null;
            /**
             * Notes
             * @default
             */
            notes: string | null;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /** Doctor Name */
            doctor_name: string;
        };
        /** ClinicalNoteResponse */
        ClinicalNoteResponse: {
            /**
             * Note Id
             * Format: uuid
             */
            note_id: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /**
             * Note Type
             * @enum {string}
             */
            note_type: "soap_subjective" | "soap_objective" | "soap_assessment" | "soap_plan" | "progress_note" | "consult_note" | "discharge_summary" | "procedure_note";
            /** Note Text */
            note_text: string;
            /** Summary */
            summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Doctor First Name */
            doctor_first_name: string;
            /** Doctor Last Name */
            doctor_last_name: string;
            /**
             * Visit Date
             * Format: date-time
             */
            visit_date: string;
        };
        /** CreatePatient */
        CreatePatient: {
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /**
             * Gender
             * @enum {string}
             */
            gender: "Male" | "Female";
            /**
             * Blood Type
             * @enum {string}
             */
            blood_type: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Address */
            address: string;
            /** Emergency Contact Name */
            emergency_contact_name: string;
            /** Emergency Contact Phone */
            emergency_contact_phone: string;
            /**
             * Allergies
             * @default []
             */
            allergies: string[];
            /**
             * Chronic Conditions
             * @default []
             */
            chronic_conditions: string[];
        };
        /** DiagnosisResponse */
        DiagnosisResponse: {
            /**
             * Diagnosis Id
             * Format: uuid
             */
            diagnosis_id: string;
            /** Patient Serial Number */
            patient_serial_number: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /** Diagnosis Code */
            diagnosis_code: string;
            /** Diagnosis Name */
            diagnosis_name: string;
            /**
             * Diagnosis Type
             * @enum {string}
             */
            diagnosis_type: "primary" | "secondary" | "chronic" | "acute";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "resolved" | "chronic";
            /**
             * Diagnosed Date
             * Format: date-time
             */
            diagnosed_date: string;
            /** Resolved Date */
            resolved_date?: string | null;
            /** Diagnosing Doctors Serial Number */
            diagnosing_doctors_serial_number: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Diagnosing Doctor First Name */
            diagnosing_doctor_first_name: string;
            /** Diagnosing Doctor Last Name */
            diagnosing_doctor_last_name: string;
        };
        /** FollowUpRequest */
        FollowUpRequest: {
            /**
             * Patient Serial Number
             * @description Patient serial number
             */
            patient_serial_number: string;
            /**
             * Doctor Serial Number
             * @description Doctor serial number
             */
            doctor_serial_number: string;
            /**
             * Visit Date
             * @description Visit date in ISO 8601 format
             */
            visit_date: string;
            /**
             * Visit Type
             * @description Type of visit
             * @default followup
             * @enum {string}
             */
            visit_type: "checkup" | "followup" | "emergency" | "specialist" | "vaccination" | "routine" | "urgent_care" | "surgical" | "telehealth";
            /**
             * Summary
             * @description Visit summary/title
             */
            summary: string;
            /**
             * Start Time
             * @description Start time in ISO 8601 format
             */
            start_time: string;
            /**
             * End Time
             * @description End time in ISO 8601 format
             */
            end_time: string;
            /**
             * Description
             * @description Visit description
             * @default
             */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LabResultResponse */
        LabResultResponse: {
            /**
             * Lab Id
             * Format: uuid
             */
            lab_id: string;
            /** Patient Serial Number */
            patient_serial_number: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /** Test Name */
            test_name: string;
            /** Result Value */
            result_value: string;
            /** Unit */
            unit?: string | null;
            /** Reference Range */
            reference_range: string;
            /**
             * Result Status
             * @enum {string}
             */
            result_status: "normal" | "abnormal" | "critical" | "pending";
            /**
             * Tested Date
             * Format: date-time
             */
            tested_date: string;
            /**
             * Received Date
             * Format: date-time
             */
            received_date: string;
            /** Ordering Doctors Serial Number */
            ordering_doctors_serial_number: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ordering Doctor First Name */
            ordering_doctor_first_name: string;
            /** Ordering Doctor Last Name */
            ordering_doctor_last_name: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Serial Number */
            serial_number: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /** Doctor Name */
            doctor_name: string;
        };
        /** MedicationResponse */
        MedicationResponse: {
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Patient Serial Number */
            patient_serial_number: string;
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /** Medication Name */
            medication_name: string;
            /** Generic Name */
            generic_name: string;
            /** Dosage */
            dosage: string;
            /** Frequency */
            frequency: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "discontinued" | "completed" | "hold";
            /** Prescribed For */
            prescribed_for: string;
            /** Instructions */
            instructions: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Prescriber First Name */
            prescriber_first_name: string;
            /** Prescriber Last Name */
            prescriber_last_name: string;
        };
        /** MedicationsRequest */
        MedicationsRequest: {
            /** Overview */
            overview: string;
            /**
             * Current Medications
             * @default []
             */
            current_medications: components["schemas"]["ActiveMedications"][];
        };
        /** Note */
        Note: {
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /**
             * Note Type
             * @enum {string}
             */
            note_type: "soap_subjective" | "soap_objective" | "soap_assessment" | "soap_plan" | "progress_note" | "consult_note" | "discharge_summary" | "procedure_note";
            /** Note Text */
            note_text: string;
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /** Summary */
            summary?: string | null;
        };
        /** OverviewRequest */
        OverviewRequest: {
            /** Overview */
            overview: string;
        };
        /** PatientBase */
        PatientBase: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /** Patient Serial Number */
            patient_serial_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Gender */
            gender: string;
            /** Blood Type */
            blood_type: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Address */
            address: string;
            /** Emergency Contact Name */
            emergency_contact_name: string;
            /** Emergency Contact Phone */
            emergency_contact_phone: string;
            /** Allergies */
            allergies?: string[];
            /** Chronic Conditions */
            chronic_conditions?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PatientFullResponse */
        PatientFullResponse: {
            patient: components["schemas"]["PatientBase"];
            /** Visits */
            visits: components["schemas"]["VisitResponse"][];
            /** Vital Signs */
            vital_signs: components["schemas"]["VitalSignsResponse"][];
            /** Medications */
            medications: components["schemas"]["MedicationResponse"][];
            /** Lab Results */
            lab_results: components["schemas"]["LabResultResponse"][];
            /** Clinical Notes */
            clinical_notes: components["schemas"]["ClinicalNoteResponse"][];
            /** Diagnoses */
            diagnoses: components["schemas"]["DiagnosisResponse"][];
        };
        /** SetVisit */
        SetVisit: {
            /** Patient Serial Number */
            patient_serial_number: string;
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /**
             * Visit Type
             * @enum {string}
             */
            visit_type: "checkup" | "followup" | "emergency" | "specialist" | "vaccination" | "routine" | "urgent_care" | "surgical" | "telehealth";
            /**
             * Location
             * @default Clinic
             */
            location: ("Clinic" | "Hospital" | "Telehealth" | "Home Visit" | "Urgent Care") | null;
            /** Visit Date */
            visit_date?: string | null;
            /**
             * Status
             * @default in-progress
             */
            status: ("scheduled" | "in-progress" | "completed" | "cancelled" | "no-show") | null;
            /**
             * Chief Complaint
             * @default
             */
            chief_complaint: string | null;
        };
        /** SignUpRequest */
        SignUpRequest: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Specialty */
            specialty: string;
            /** License Number */
            license_number: string;
            /** Password */
            password: string;
        };
        /** UpdateAllergies */
        UpdateAllergies: {
            /** Allergies */
            allergies: string[];
        };
        /** UpdateMedication */
        UpdateMedication: {
            /** Dosage */
            dosage?: string | null;
            /** Frequency */
            frequency?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Status */
            status?: ("active" | "discontinued" | "completed" | "hold") | null;
            /** Prescribed For */
            prescribed_for?: string | null;
            /** Instructions */
            instructions?: string | null;
        };
        /** UpdateVisit */
        UpdateVisit: {
            /** Chief Complaint */
            chief_complaint: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "in-progress" | "completed" | "cancelled" | "no-show";
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitResponse */
        VisitResponse: {
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /** Patient Serial Number */
            patient_serial_number: string;
            /** Doctor Serial Number */
            doctor_serial_number: string;
            /**
             * Visit Date
             * Format: date-time
             */
            visit_date: string;
            /**
             * Visit Type
             * @enum {string}
             */
            visit_type: "checkup" | "followup" | "emergency" | "specialist" | "vaccination" | "routine" | "urgent_care" | "surgical" | "telehealth";
            /** Chief Complaint */
            chief_complaint: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "in-progress" | "completed" | "cancelled" | "no-show";
            /** Duration Minutes */
            duration_minutes: number;
            /** Location */
            location: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Doctor First Name */
            doctor_first_name: string;
            /** Doctor Last Name */
            doctor_last_name: string;
            /** Specialty */
            specialty: string;
        };
        /** VitalSignsResponse */
        VitalSignsResponse: {
            /**
             * Vital Id
             * Format: uuid
             */
            vital_id: string;
            /**
             * Visit Id
             * Format: uuid
             */
            visit_id: string;
            /**
             * Measurement Time
             * Format: date-time
             */
            measurement_time: string;
            /** Blood Pressure Systolic */
            blood_pressure_systolic: number;
            /** Blood Pressure Diastolic */
            blood_pressure_diastolic: number;
            /** Heart Rate */
            heart_rate: number;
            /** Temperature */
            temperature: number;
            /** Respiratory Rate */
            respiratory_rate: number;
            /** Oxygen Saturation */
            oxygen_saturation: number;
            /** Weight Kg */
            weight_kg: number;
            /** Height Cm */
            height_cm: number;
            /** Bmi */
            bmi: number;
            /** Pain Level */
            pain_level: number;
            /** Notes */
            notes: string;
            /**
             * Visit Date
             * Format: date-time
             */
            visit_date: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_patients_api_patients_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_patients_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatient"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_patient_api_patients_search_get: {
        parameters: {
            query: {
                patient_serial_number: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_api_patients__patient_serial__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientFullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_note_api_patients__patient_serial__notes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_medication_api_patients__patient_serial__medications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMedication"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_medication_api_patients__patient_serial__medications__medication_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
                medication_id: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMedication"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_medication_api_patients__patient_serial__medications__medication_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
                medication_id: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vitals_api_patients__patient_serial__vitals_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddVitalSigns"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_lab_api_patients__patient_serial__labs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLabResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_diagnosis_api_patients__patient_serial__diagnoses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDiagnosis"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_allergies_api_patients__patient_serial__allergies_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAllergies"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_visit_api_patients_visits_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVisit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_visit_api_patients_visits_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetVisit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visit_report_api_patients__patient_serial__visits__visit_id__report_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
                visit_id: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_agents_overview__patient_serial__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                patient_serial: string;
            };
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_agents_recommendations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_medications_api_agents_medications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_visit_api_agents_schedule_followup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    authorize_api_auth_google_authorize_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_auth_google_callback_get: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_auth_google_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_dashboard_stats_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_dashboard_schedule_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breakdown_api_dashboard_breakdown_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lab_alerts_api_dashboard_lab_alerts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_diagnoses_api_dashboard_top_diagnoses_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ha_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
