services:
  postgres:
    image: postgres:18
    container_name: ha-postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/18/docker
      - ./db/data:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - ha-network

  server:
    build: ./server
    container_name: ha-server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - ha-network

networks:
  ha-network:
    driver: bridge

volumes:
  postgres-data:
